package com.asus.zenmotions.util;

public class ActionConstants {
    public static final String ACTION_APP = "**app**";
    public static final String ACTION_ASSIST = "**assist**";
    public static final String ACTION_BACK = "**back**";
    public static final String ACTION_CAMERA = "**camera**";
    public static final String ACTION_DELIMITER = "|";
    public static final String ACTION_EXPANDED_DESKTOP = "**expanded_desktop**";
    public static final String ACTION_HOME = "**home**";
    public static final String ACTION_IME = "**ime**";
    public static final String ACTION_IME_NAVIGATION_DOWN = "**ime_nav_down**";
    public static final String ACTION_IME_NAVIGATION_LEFT = "**ime_nav_left**";
    public static final String ACTION_IME_NAVIGATION_RIGHT = "**ime_nav_right**";
    public static final String ACTION_IME_NAVIGATION_UP = "**ime_nav_up**";
    public static final String ACTION_KEYGUARD_SEARCH = "**keyguard_search**";
    public static final String ACTION_KILL = "**kill**";
    public static final String ACTION_LAST_APP = "**lastapp**";
    public static final String ACTION_MEDIA_NEXT = "**media_next**";
    public static final String ACTION_MEDIA_PLAY_PAUSE = "**media_play_pause**";
    public static final String ACTION_MEDIA_PREVIOUS = "**media_previous**";
    public static final String ACTION_MENU = "**menu**";
    public static final String ACTION_MENU_BIG = "**menu_big**";
    public static final String ACTION_NAVBAR = "**nav_bar**";
    public static final String ACTION_NOTIFICATIONS = "**notifications**";
    public static final String ACTION_NULL = "**null**";
    public static final String ACTION_PIE = "**pie**";
    public static final String ACTION_POWER = "**power**";
    public static final String ACTION_POWER_MENU = "**power_menu**";
    public static final String ACTION_RECENTS = "**recents**";
    public static final String ACTION_SCREENSHOT = "**screenshot**";
    public static final String ACTION_SEARCH = "**search**";
    public static final String ACTION_SILENT = "**ring_silent**";
    public static final String ACTION_THEME_SWITCH = "**theme_switch**";
    public static final String ACTION_TORCH = "**torch**";
    public static final String ACTION_VIB = "**ring_vib**";
    public static final String ACTION_VIB_SILENT = "**ring_vib_silent**";
    public static final String ACTION_VOICE_SEARCH = "**voice_search**";
    public static final String ACTION_WAKE_DEVICE = "**wake_device**";
    public static final String ICON_EMPTY = "empty";
    public static final String NAVIGATION_CONFIG_DEFAULT = "**back**|**null**|empty|**home**|**null**|empty|**recents**|**null**|empty";
    public static final String NAV_RING_CONFIG_DEFAULT = "**assist**|**null**|empty";
    public static final String PIE_SECOND_LAYER_CONFIG_DEFAULT = "**power_menu**|**null**|empty|**notifications**|**null**|empty|**search**|**null**|empty|**screenshot**|**null**|empty|**ime**|**null**|empty";
    public static final String SYSTEM_ICON_IDENTIFIER = "system_shortcut=";
}
